### PR TITLE
Chores/gaunltet core 0.1.0 upgrade

### PR DESCRIPTION
**Pull request by sdrug**

### CODE REVIEW

**Review by krebernisak — APPROVED** [review]
LGTM!

**Review by RodrigoAD — APPROVED** [review]
LGTM too. Feel free to merge

**Comment by krebernisak** [comment]
@sdrug is this ready to merge or are some things still pending?

**Comment by sdrug** [comment]
@krebernisak upgraded to gauntlet-core v0.1.2 (fixed bug on help command), could approve once again?

**Comment by RodrigoAD** [comment]
@sdrug Please run `yarn` again. `yarn.lock` needs to be updated too

**Review by krebernisak — DISMISSED** [review]

**Review by RodrigoAD — APPROVED** [review]

**Pull request merged**
